### ISSUE TITLE
Unknown Exception at launch

### ISSUE THREAD

**Issue by BrioMerKury** [Leo40Git/OneShot-Textbox-Maker#5]
**Version (don't say "latest"): OSTBM-2.1** 

**Link to obstm.log (pastebin/gist): https://pastebin.com/QiVRYU9b** 

----

**Description of what you were doing when the issue happened: I opened the .jar file and the message of an unknown exception pops up**

**Comment by Leo40Git** [comment]
"2020-05-07 **00:06**:10.905"
why you makin OneShot textboxes at 12PM :confused:

**Comment by Leo40Git** [comment]
Fixed in 2.2. Unfortunately, this crash happens before auto-update can kick in, so you'll have to update it manually.
