### ISSUE TITLE
\i fails to interrupt current textbox

### ISSUE THREAD

**Issue by HokoraYinphineMPP** [Leo40Git/OneShot-Textbox-Maker#6]
**Version: 2.2** 
**Java Version: 8 Update 271 (build 1.8.0_271-b09)**

----

**"\i" fails to interrupt current textbox** 
![image](https://user-images.githubusercontent.com/54823358/102172823-72d70f00-3e4e-11eb-81f5-fa9b69ae367c.png)
![interrupt test](https://user-images.githubusercontent.com/54823358/102172851-82565800-3e4e-11eb-8716-7660389e6142.gif)

**Comment by Leo40Git** [comment]
Fixed in v2.2.1

**Comment by HokoraYinphineMPP** [comment]
ty <3
