### ISSUE TITLE
Incorrect modifier positions

### ISSUE THREAD

**Issue by Apceniy** [Leo40Git/OneShot-Textbox-Maker#9]
**Version (don't say "latest"):** 2.2.2

**Link to ostbm.log (pastebin/gist):** https://pastebin.com/iFxuQbG4

----

**Description of what you were doing when the issue happened:** I was making textboxes, obviously.
The bug is that for N line modifier positions are shifted to the beginning by N-1 symbols.
You can see this clearly if you use this text:
> test1\d[30]test2
> test3\d[30]test4
> test5\d[30]test6
> test7\d[30]test8

![clipboard](https://user-images.githubusercontent.com/53149450/163252187-09368a27-734d-49e5-aa8d-1b17e6d080eb.gif)
Notice that for every next line the delay is happening 1 symbol earlier than on the previous line.

**Comment by Apceniy** [comment]
This is happening because you don't count line breaks as symbols when calculating positions.
The bug can be fixed by adding `modPos++;` to TextboxUtil.java after line 199.
I cloned the repo, added the line, built the project, and the problem was fixed.

**Comment by Leo40Git** [comment]
Sorry for the lack of response, I was away from my computer.
This fix will be included in a hotfix release tomorrow!

**Comment by Leo40Git** [comment]
2.2.3 contains this fix!
